Koi/config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { registrations: 'registrations' }
  resources :users, only: [:show]

  resources :topics do
    resources :unit_of_educations do
      member do
        patch :complete
      end
    end
  end

  root 'topics#index'
end

Koi/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

Koi/app/models/concerns/uses_default_assets.rb
module UsesDefaultAssets

	def random_avatar_image_path
		dir_name =default_avatar_path
		file_name = sample_file(dir_name,/\.png/)
		dir_name.concat file_name
	end

	def random_topic_image_path
		dir_name =default_topic_image_path
		file_name = sample_file(dir_name,/\.svg/)
		dir_name.concat file_name
	end

	private
		def default_avatar_path
			Rails.root.to_s.concat "/app/assets/images/profiles/"
		end

		def default_topic_image_path
			Rails.root.to_s.concat "/app/assets/images/topics/"
		end

	def sample_file dir, extension
			Dir.open(dir).to_a.select {|f| f.downcase.match(extension) }.sample
	end
end

Koi/app/models/topic.rb
class Topic < ApplicationRecord
  include UsesDefaultAssets

  validates_presence_of :title, :description, :max_units
  validates :max_units, :numericality => { :greater_than => 0}, :on => :save

  has_many :unit_of_educations

  belongs_to :user
  has_one_attached :image

  before_save :check_completion

  before_create :set_default_image

  def total_points_value
    sum_points unit_of_educations
  end

  def completed_points_value
    sum_points completed_units
  end

  def units_remaining
    max_units - completed_units.size
  end

  def completed_units
    unit_of_educations.select{|unit| unit.completed?}
  end

  def completed?
    #  cannot be zero
    unit_of_educations.size>0 &&  units_remaining.equal?(0)
  end

  private

  def sum_points units_to_sum
    units_to_sum.map(&:points).inject(0, &:+)
  end

  def check_completion
      if completed? && complete_date.nil?
        update_attribute(:complete_date, Time.now)
      end
  end

  def set_default_image
    image_path = random_topic_image_path
    self.image.attach(io: File.open(image_path), filename: File.basename(image_path))
  end

end

Koi/app/models/unit_of_education.rb
class UnitOfEducation < ApplicationRecord
  validates_presence_of :title, :points
  belongs_to :topic

  def completed?
    !completed_at.blank?
  end
end

Koi/app/models/user.rb
class User < ApplicationRecord
  include UsesDefaultAssets
  has_many :topics
  validates_presence_of :name

  has_one_attached :avatar

  before_create :set_default_avatar

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  private

  def set_default_avatar
    image_path = random_avatar_image_path
    self.avatar.attach(io: File.open(image_path), filename: File.basename(image_path))
  end
end

Koi/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!

  def not_found
    raise ActionController::RoutingError.new('Not Found')
  end

end

Koi/app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

	private

	def sign_up_params
		params.require(:user).permit(:name, :email, :password, :password_confirmation)
	end

	def account_update_params
		params.require(:user).permit(:name, :email, :password, :avatar, :password_confirmation, :current_password)
	end
end

Koi/app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  helper TopicHelper

  before_action :authenticate_user!
  before_action :find_topic, only: [:show, :destroy, :update, :edit]
  before_action :requires_same_user, only: [:edit,:show, :update, :destroy]

  def create
    @topic = current_user.topics.build(topic_params)

    if @topic.save
      redirect_to root_path
    else
      render 'new'
    end
  end
  def new
    @topic = current_user.topics.build
  end

  def index
    @topics = current_user.topics
  end

  def destroy
    @topic.destroy
    redirect_to root_path
  end

  def update
    if @topic.update(topic_params)
      redirect_to @topic, notice: "Updated!"
    else
      render 'edit'
    end
  end

  def edit

  end

  def show
    @topic = Topic.find(params[:id])
  end

  private
  def topic_params
    params.require(:topic).permit(:title,:description,:max_units)
  end

  def find_topic
    @topic = Topic.find(params[:id])
  end

  def requires_same_user
    unless current_user.id === @topic.user.id
      redirect_to root_path, alert: "You are not able to perform this action."
    end
  end
end

Koi/app/controllers/unit_of_educations_controller.rb
class UnitOfEducationsController < ApplicationController
  before_action :authenticate_user!
  before_action :find_topic
  before_action :find_uoe, only: [:edit,:update,:destroy,:complete]
  before_action :requires_same_user, only: [:complete, :edit, :update, :destroy]

  def new
    @uoe = @topic.unit_of_educations.build

  end

  def complete
      @uoe.update_attribute(:completed_at, Time.now)

      if @uoe.save
        redirect_to(@topic)
      else

      end
  end

  def create
    @uoe = @topic.unit_of_educations.build(uoe_params)

    if @uoe.save
      redirect_to topic_path(@topic)
    else
      render 'new'
    end
  end

  def edit

  end

  def update
    if @uoe.update(uoe_params)
      redirect_to @topic, notice: 'Updated!'
    else
      render 'edit'
    end
  end

  def destroy
    @uoe.destroy
    redirect_to topic_path(@topic)
  end

  private
    def uoe_params
      params.require(:unit_of_education).permit(:title,:description,:points)
    end

    def find_uoe
      @uoe = UnitOfEducation.find(params[:id])
    end
    def find_topic
      @topic = Topic.find(params[:topic_id])
    end


    def requires_same_user
      unless current_user.id === @uoe.topic.user.id
        redirect_to root_path, alert: "You are not able to perform this action."
      end
    end
end

Koi/app/controllers/users_controller.rb
class UsersController < ApplicationController
  helper UserHelper

  before_action :find_user, only: [:show]

  ## Can see public profiles
  skip_before_action :authenticate_user!, only: [:show]

  def show

  end

  private
    def find_user
      @user = User.find(params[:id])
    end
end

Koi/app/helpers/application_helper.rb
module ApplicationHelper
end

Koi/app/helpers/registrations_helper.rb
module RegistrationsHelper
end

Koi/app/helpers/topic_helper.rb
module TopicHelper
	include UsesDefaultAssets

	def topic_image topic
		if topic.image.attached?
			image_tag topic.image
		end
	end

	def last_active_time topic
		topic.updated_at.to_formatted_s(:long_ordinal)
	end
end

Koi/app/helpers/units_of_education_helper.rb
module UnitsOfEducationHelper
end

Koi/app/helpers/user_helper.rb
module UserHelper

	def user_avatar user
		if user.avatar.attached?
			image_tag  user.avatar,class:"is-rounded"
		end
	end

	def completed_topics user
		user.topics.select{|topic| topic.completed?}
	end

	def current_user_owns_profile user
		if user
			current_user.id.equal?(user.id)
		end
	end
end

Koi/app/views/layouts/_empty_topics_notification.html.erb
<article class="message">
  <div class="message-body">
    <%= @user.name %> has not completed any topics yet.
  </div>
</article>

Koi/app/views/layouts/_footer.html.erb
<footer class="footer">
    <div class="has-text-centered">
      <p>
        <strong>Koi </strong> made in Waterloo</a>.
      </p>
    </div>
</footer>

Koi/app/views/layouts/_navigation.html.erb
<header>
  <nav class="navbar" role="navigation" aria-label="main navigation">
    <div class="navbar-brand">
      <%= link_to image_tag("logo.svg", :alt => "Koi Logo"), root_path, class: "logo" %>
    </div>
    <% if user_signed_in? %>
        <div class="navbar-start">
          <%= link_to "New Topic", new_topic_path, class: "navbar-item" %>
        </div>
        <div class="navbar-end">
          <div class="navbar-item has-dropdown is-hoverable">
            <a href="#" class="navbar-link"></a>

            <div class="navbar-dropdown is-right">
              <%= link_to "Profile", user_path(current_user), class: 'navbar-item' %>
              <hr class="navbar-divider">
              <%= link_to "Logout", destroy_user_session_path, method: :delete, class:"navbar-item" %>
            </div>
          </div>
        </div>
    <%else%>
        <div class="navbar-end">
          <div class="navbar-item">
            <%= link_to "Login", new_user_session_path  %>
          </div>
          <div class="navbar-item">
            <%= link_to "Sign Up", new_user_registration_path, class: 'button is-info' %>
          </div>
        </div>
        </div>
    <%end%>
  </nav>
</header>

Koi/app/views/layouts/_notification.html.erb
<div class="message fader is-warning floater">
  <div class="message-body">
    <%= notice if notice %>
    <%= alert if alert %>
  </div>
</div>

Koi/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Koi: Get Learning</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <% if user_signed_in?%>
         <%= render 'layouts/navigation'  %>
    <%end%>

    <div id="main-content">

      <%= render "layouts/notification" if notice || alert %>

      <%= yield %>

    </div>
    <%= render 'layouts/footer'%>

  </body>
</html>

Koi/app/views/users/show.html.erb
<section class="hero is-small is-primary is-bold">
  <div class="container">
    <p class="margin-top">
        <%= link_to_if current_user_owns_profile(@user), 'Edit Profile', edit_user_registration_path(@user), class: 'is-pulled-right' do
            nil
          end
        %>
    </p>
  </div>

  <div class="hero-body">
    <div class="container">
      <div class="columns">
        <div class="column is-2">
          <figure class="image is-128x128">
              <%= user_avatar(@user) %>
          </figure>
        </div>
        <div class="column is-10">
          <br/>
          <h1 class="title">
            <%= @user.name %>
          </h1>
          <h2 class="subtitle is-size-6">
            Member since <%= @user.created_at.strftime("%d %B %Y") %>
          </h2>
        </div>
      </div>
    </div>
  </div>
</section>

<br/>
<div class="container">
    <h3 class="title is-size-5"> Topics Completed </h3>
  <br/>

    <%= render "layouts/empty_topics_notification" unless completed_topics(@user).size > 0 %>
    <% completed_topics(@user).each do |t| %>
        <p><%= t.title %></p>
    <% end %>

</div>