FileCab/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'welcome/index'
  resources :docs

  authenticated :user do
    root "docs#index", as: "authenticated_root"
  end
  root 'welcome#index'
end

FileCab/app/models/doc.rb
class Doc < ApplicationRecord
    belongs_to :user
    
end

FileCab/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :docs
end

FileCab/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

FileCab/app/controllers/docs_controller.rb
class DocsController < ApplicationController

    before_action :find_doc, only: [:show,:edit,:update,:destroy]
   
    def index 
        @docs = Doc.where(user_id: current_user) 
        # Only display documents that belong to user.

    end
    def show 
       find_doc
    end
    def new 
        @doc = current_user.docs.build
    end
    def create 
        @doc = current_user.docs.build(doc_params)

        if @doc.save
            redirect_to @doc
        else
            render 'new'
        end
    end

    def edit 
    end
    def update 
        if @doc.update(doc_params)
            redirect_to @doc
        else
            render 'edit'
            # Render vs redirect, because redit is an http action
        end 
    end
    def destroy 
        @doc.destroy
        redirect_to docs_path
    end
    
    private 
        def find_doc
            # By rails convention, anything you need more than once you should make a method for DRY
            @doc = Doc.find(params[:id])
        end

        def doc_params
            params.require(:doc).permit(:title,:content)
        end 
end

FileCab/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

FileCab/app/helpers/docs_helper.rb
module DocsHelper
end

FileCab/app/helpers/welcome_helper.rb
module WelcomeHelper
end

FileCab/app/views/docs/_form.html.haml
= simple_form_for @doc do |f|
    = f.input :title
    = f.input :content
    = f.button :submit, class: 'button-f'

FileCab/app/views/docs/edit.html.haml
.wrapper_with_padding
    %h1 Fix Document

    = render 'form'
    %br
    = link_to "Cancel", doc_path

FileCab/app/views/docs/index.html.haml
.wrapper_with_padding
    #docs.clearfix
        - unless @docs.blank?
            - @docs.each do |doc|
                %a{href: (url_for [doc])}
                    .doc
                        %p.title= doc.title
                        %p.date= time_ago_in_words(doc.created_at)
                        %p.content= truncate(doc.content, length:50)
        - else 
            %h2 Create Document
            %p.new_doc Create a new note or document now
            %button= link_to "Create Document", new_doc_path

FileCab/app/views/docs/new.html.haml
.wrapper_with_padding

    %h1 New Document
    = render 'form'

FileCab/app/views/docs/show.html.haml
.wrapper_with_padding
    #doc_show
        %h1.title= @doc.title
        %p= @doc.content

        %br
        = link_to'Edit', edit_doc_path(@doc)
        = link_to 'Trash', doc_path(@doc), class: 'pull-right', method: :delete, data: {confirm: "are you sure?"}

FileCab/app/views/layouts/application.html.haml
!!! 
%html
%head 
  %title FileCab | Everything You Need!
  = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
  = javascript_include_tag 'application', 'data-turbolinks-track' => true
  = csrf_meta_tags
  
%body
  %header
    .header_inner
      = link_to('FileCab', root_path, id: "logo")

      %nav
        - if user_signed_in?
          = link_to "Create Doc", new_doc_path
          = link_to "Sign Out", destroy_user_session_path, method: :delete

        - else 
          = link_to "Login", new_user_session_path
    %p.notice= notice
    %p.alert= alert

  = yield