Doist/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :items do
    member do
      patch :complete
    end
  end
  
  root 'items#index'
  
end

Doist/app/models/item.rb
class Item < ApplicationRecord
    belongs_to :user

    def completed?
        !completed_at.blank?
    end
end

Doist/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :items
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

Doist/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  def after_sign_in_path_for(resource_or_scope)
    items_path
  end
  
  def after_sign_out_path_for(resource_or_scope)
    new_user_session_path
  end
end

Doist/app/controllers/items_controller.rb
class ItemsController < ApplicationController
    before_action :find_item, only: [:show,:edit,:update,:destroy]

    def index
        if user_signed_in?
            @items = Item.where(:user_id => current_user.id).order("created_at DESC")
        end
    end 
    
    def new
        @item = current_user.items.build
    end

    def show
       
    end

    def edit
    end

    def update
        if @item.update(item_params)
            redirect_to @item, notice: "Updated"
        else 
            render 'edit'
        end
    end 

    def complete
        @item = Item.find(params[:id])
        @item.update_attribute(:completed_at, Time.now)
        redirect_to root_path
    end

    def destroy
        @item.destroy
        redirect_to root_path
    end

    def create
        @item = current_user.items.build(item_params)

        if @item.save
            redirect_to root_path
        else
            render 'new'
        end

    end

    private
        def find_item
            @item = Item.find(params[:id])
        end

        def item_params
            params.require(:item).permit(:title, :description)
        end
end

Doist/app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def index
    end
end

Doist/app/helpers/items_helper.rb
module ItemsHelper
end

Doist/app/helpers/pages_helper.rb
module PagesHelper
end

Doist/app/views/items/_form.html.erb
<%= simple_form_for @item do |f| %>
    <%= f.input :title, label: "Task", class: 'input-field'%>
    <%= f.input :description, label: "Description", class: 'input-field'%>
    <%= f.button :submit, class: 'blue'%>
<%end%>

Doist/app/views/items/_welcome_page.html.erb
<div class="main-content">
<div class='bg'></div>
    <div class="jumbotron">
        <div class="content-inverse">
        <br/><br/><br/>
        <h1> Finally. Tasks Done. </h2>
        <h5> Doist is a beautiful Todo list for you! </h5>
        </div>
    </div>

    <br/>
    <div class="row">
        <div class="col m6">
            <h3> Why Doist? </h3>
            <div class="divider"></div>
            <p> Doist is the next level innovation in Todo list technology. With unfoundingly average performance, and great design. Doist provides users with a keen sense of control to take back their chaotic schedules and days, to emerge as victors. </p>
            <%= link_to "Sign Up", new_user_registration_path, class: 'btn blue'%>
            </div>

        <div class="col m6">
            <h3> Already A Member? </h3>
            <div class="divider"></div>
            <p> Welcome back! Ready to get some work done? Login below ! </p>
            <br/>
            <%= link_to "Login", new_user_registration_path, class: 'btn blue'%>
        </div>
    </div>
  

</div>

Doist/app/views/items/edit.html.erb
<div class="main-content">
    <h2> Edit </h2>
    <%= render 'form' %>
</div>

Doist/app/views/items/index.html.erb
<% if user_signed_in? %>
<div class="row">
    <div class="col s9">
    <ul class="collection with-header z-depth-3">
        <li class="collection-header"><h4>Your List </h4></li>
        <% @items.each do |item| %>
            <% if item.completed? %>
            <li class="collection-item todo-item">
                <div class="row">
                  <!-- Trash -->
                    <div class="col s2">
                        <p> <%= link_to item, method: :delete do %></p>
                        <i class="material-icons md-24">delete</i>
                        <%end%>
                    </div>
               
                 <div class="col s8">
                        <h4 style="opacity: 0.5; text-decoration: line-through;"><%= link_to item.title, item %></h4>
                        <p style="opacity: 0.5;"><%= item.description%></p>
                        <p style="opacity: 0.5;"> Completed <%= time_ago_in_words(item.completed_at) %> ago </p>
                    </div>

                  
                </div>
             </li>

            <% else %>
            <li class="collection-item todo-item">
                <div class="row">   
                    <div class="col s8">
                    
                        <h4 style=""><%= link_to item.title, item %></h4>
                        <p style=""><%= item.description%></p>
                        <p style=";"> Created <%= time_ago_in_words(item.created_at) %> ago </p>
                  
                </div>
                 <!-- Complete -->
                <div class="col s2">
                    <p> <%= link_to complete_item_path(item), method: :patch do %></p>
                     <i class="material-icons md-24">check</i>
                     <%end%>
                </div>

                 <!-- Trash -->
                <div class="col s2">
                    <p> <%= link_to item, method: :delete do %></p>
                     <i class="material-icons md-24">delete</i>
                     <%end%>
                </div>
                </div>
              </li>
            <%end%>
        <%end%>
    </div>

    <div class="col s3">
    <ul class="collection with-header z-depth-3">
        <li class="collection-header"><h5>Pinned Items</h5></li>
    </ul>
    </div>
</ul>
<% else %>
    <%= render 'welcome_page'%>
<%end%>

Doist/app/views/items/new.html.erb
<div class="main-content">
    <h2> New Todo Item </h2>
    <%= render 'form' %>
</div>

Doist/app/views/items/show.html.erb
<div class="col-md-10 cd-md-offset-1" style="background: white; padding:1em;">
    <h2><%= @item.title %></h2>
    <p><%= @item.description %> </p>
    <%= link_to "Edit", edit_item_path, class: 'waves-effect waves-light btn blue' %>
    <%= link_to "Destroy", item_path, method: :delete, data: {confirm: "Are you sure?"}, class: "waves-effect waves-light btn red"%>
</div>